### ISSUE TITLE
Align educativity graphs

### ISSUE THREAD

**Issue by Sam-TNO** [basvdl97/PQChoiceAssistant#18]
It would be nice if all of the graphs were aligned vertically, both on the left and the right.
Right now there is some variation due to the numbers displayed to the left, but it looks nice if the graphs are directly below each other, with some space between the graph and the number if needed.

Also it is nice if the line with the quantities (so "Performance (cycles)" and "Size (bytes)") is aligned to the right of the graph instead.

@basvdl97 I think you mentioned that you were still working on Erik's design, so apologies if you were already planning to do these things.

**Comment by basvdl97** [comment]
Done
