### ISSUE TITLE
Translation - small things

### ISSUE THREAD

**Issue by Sam-TNO** [basvdl97/PQChoiceAssistant#21]
There are a few things left that need to be translated:
- [x] The button at the end of the questionnaire should say "results" in English
- [x] The categories of the education table should be translated in the Dutch version. I added the text to the JSON here https://github.com/basvdl97/PQChoiceAssistant/commit/3e692b47f6cf89f10ba472286ab8b87494e13caa, but it might not be the best format
- [x] The menu at the top needs to be translated in the Dutch version
- [x] Also on the menu, I think "Enc/DSAChoiceAssistant" should be "KEM/DSA questionnaire", and the text "Git repo" should be removed. This should be checked with @maaikevanleuken
- [x] I still need to translate the text of the pairwise algorithm comparisons

**Comment by maaikevanleuken** [comment]
Can you make it "GitHub" + logo? Thanks
