### ISSUE TITLE
Use of scoring_question field

### ISSUE THREAD

**Issue by Sam-TNO** [basvdl97/PQChoiceAssistant#26]
I could be mistaken, but I don't think this flag is being used yet in the scoring logic.

Each question has a flag `scoring_question`. If this is false, the question should not be taken into account for the final scoring, so the variable counting the number of questions answered by the user (I think it was `n`) should not be incremented in this case.

**Comment by basvdl97** [comment]
@Sam-TNO

So if scoring_question is false. `n` should not be incremented & the answer's scores should not be counted.
