### ISSUE TITLE
Button blocks text

### ISSUE THREAD

**Issue by maaikevanleuken** [basvdl97/PQChoiceAssistant#32]
![image](https://github.com/user-attachments/assets/b5a3ff07-3b27-4b3a-b2d0-cc37bb650e11)

**Comment by basvdl97** [comment]
I will make the button sit below the content instead of be fixed at the bottom of the page.

Perhaps it needs to be located somewhere at the top instead. Like withe questionair stepper. Otherwise users might "lose" the button off page, needing to scroll down.

@maaikevanleuken opinions?

**Comment by basvdl97** [comment]
Changed, and looks fine imo.
