### ISSUE TITLE
Back button refers to wrong page

### ISSUE THREAD

**Issue by maaikevanleuken** [basvdl97/PQChoiceAssistant#33]
"Als ik van de resultatenpagina van de EncChoiceAssistant op de terugknop in de browser (en dus niet de “Back to questions” knop op de pagina) klik, land ik op de vragenpagina van de DSAChoiceAssistant en andersom"

**Comment by basvdl97** [comment]
Can you please describe any specific actions you took to achieve this bug.

I can currently not recreate this bug on my local machine, nor on the deployed version.

@maaikevanleuken
