### ISSUE TITLE
Standardisation logic

### ISSUE THREAD

**Issue by Sam-TNO** [basvdl97/PQChoiceAssistant#37]
For the question "Which standardisation bodies do you have to follow surrounding PQC algorithms?", the client would like the logic to be slightly different.
If the user checks multiple boxes, this means that they have to follow *at least one* of the selected options, but not necessarily all of them.
For the implementation, this means that (for this question only) the score for each algorithm should be the maximum of the chosen answers, rather than the average. Also, an algorithm should only be disqualified if *all* selected answers give that algorithm a score of -1.

**Comment by basvdl97** [comment]
@Sam-TNO Om te zorgen dat deze functionalitijd om een nette manier geimplementeerd kan worden, is het fijn als er niet naar een string of de index van deze specifiek vraag gekeken hoeft te worden, aangezien die nog wel eens zouden kunne veranderen.

Ik stel voor dat er aan een vraag een bool aan de vraag wordt toegevoegt, net als `expert_level` waarop we kunnen checken of de antworden als OR behandelt moeten worden.

**Comment by Sam-TNO** [comment]
Ik heb inderdaad een `custom_scoring` boolean toegevoed, die is voor alle andere vragen `NaN` maar hier dus `"OR"`. Ik heb dit als een string gedaan om mogelijk later nog andere soorten toe te kunnen voegen, zie https://github.com/basvdl97/PQChoiceAssistant/commit/47f023248c59746e5489ebaedc6ce885e17e78b2. Daar zou je dus op kunnen checken.

**Comment by basvdl97** [comment]
Okay.

Als customer_scoring een string is. Dan is NaN (not a number) een beetje raar.

Ik pas het aan naar null/false.
