### ISSUE TITLE
Translations education graphs

### ISSUE THREAD

**Issue by Sam-TNO** [basvdl97/PQChoiceAssistant#42]
I noticed that some words were not translated to Dutch on the education graph page.
I added the translation to the JSONs (part of https://github.com/basvdl97/PQChoiceAssistant/commit/c585b128f48320f2a740ba6f3eb21c34fa191732), but this still needs to be handled by the logic.

The titles ("Performance", "Grootte") and the categories ("Sleutelgeneratie", "Publieke sleutel", etc) all need to be displayed in the correct language. And the text "Text (NL)" should not be displayed as a bar graph.

**Comment by basvdl97** [comment]
@Sam-TNO Kun je de vertraling op de zelfde manier toevoegen als bij de andere json's. Met de language code, niet met `Text (NL)`.

Maar:
```json
{
      NL: '...',
      EN: '...'
}
```

Kun je ook zorgen dat ze achter een geschijden key staan en niet tussen de algo's. Anders moet i dat op een `lelijke` manier er uit filteren elke keer als ik door de algo's loop.

Alvast bedankt.

**Comment by Sam-TNO** [comment]
Ik heb het nu inderdaad op de "goede" manier veranderd, zie https://github.com/basvdl97/PQChoiceAssistant/commit/f56d954c0644febbcfd0683d5858127ca1297717. Ik hoop dat het zo makkelijker gaat.

**Comment by basvdl97** [comment]
Bedankt, je maakt het wel een uitdaging voor me door de structuur helemaal te verenden 😂
